Ot193 16
alkemyTech/OT193-Server pull request #10
Opened 2022-05-03 00:17 UTC by fa310

Creación de Entidad Role, Repositorio Controllers e inicio del método save.

2022-05-03 01:19 UTC, duccisg requested changes
- Vamos a usar como repo de BBDD H2, modifica esto del app properties.

- Cambiá LocalDate por LocalLocalDateTime

- Utilizá esta logica para persistir de forma automatica el horario de persistencia de la entidad.

@PrePersist
private void beforePersisting() {
this.createDate= LocalDateTime.now();
}

2022-05-03 01:47 UTC, duccisg commented
@fa310  revisá los conflictos que tenes con los cambios que subió un compañero en las clases de categoria

2022-05-03 19:20 UTC, fa310 commented
[Corrección conflicto con la rama Category]

2022-05-05 18:25 UTC, fa310 commented
Arreglo de los conflictos en pom.xml, aplicationproperties, y OngApplication

2022-05-06 17:13 UTC, duccisg approved these changes

2022-05-06 17:21 UTC, merged