CRUD entidad slides
alkemyTech/OT193-Server pull request #66
Opened 2022-05-26 22:22 UTC by cristhianGutierrez

2022-05-28 20:18 UTC, duccisg requested changes

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +                Slide ultSlide=listSlide.get(listSlide.size()-1);
esto es una busqueda a la base de datos directo de la siguiente posicion del slide, buscas el ultimo y le sumas uno directamente en la query sin hacer el mapeo de todo y una busqueda de todo

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +	public boolean existSlideByOrder(Integer order){
no tiene que ser un metodo esta validación, se llama directo al repositorio

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +	public boolean existSlideById(Long id){
no tiene que ser un metodo esta validación, se llama directo al repositorio

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +	public boolean existOrganizationById(Long id){
no tiene que ser un metodo esta validación, se llama directo al repositorio

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +    public Organization getOrganizationId(Long id) {
no tiene que ser un metodo esta validación, se llama directo al repositorio

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +    public List<SlidesGetDTO> getAll() throws Exception {
el nombre tiene que ser mas declarativo, getAllSlides

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +			throw new Exception("Lista vacia ");
por qué una lista vacia genera una excepción ? en caso de usar excepciones, tienen que ser las excepciones custom

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/controllers/SlideController.java
> +			response.put("mensaje", "Ocurrio un error al listar Slides ");
una excepcion no es siempre un 404 , este punto no está bien, un 404 es que no existe el recurso, para tu caso de uso, se devuelve una lista sin elementos en el get all

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/controllers/SlideController.java
> +		 } catch (Exception e) {
Todas las exception no son errores http 404, usa excepciones custom que especifiquen el error en cuestión, ModelNotFoundException, fijate las excepciones que hicieron tus compañeros

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/controllers/SlideController.java
> +		 } catch (Exception e) {
idem manejo de excepciones vs HTTP status code

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/controllers/SlideController.java
> +        } catch (Exception e) {
idem manejo de excepciones vs HTTP Codes

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/controllers/SlideController.java
> +		 } catch (Exception e) {
idem excepciones vs http status codes

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +		 boolean existOrganization= organizationRepository.existsById(organizationId);
la organización la tenes que buscar despues de validar todos los datos de forma correcta, sino estas desperdiciando recursos

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +            }else if(slideDTO.getEncodeImg()== null || slideDTO.getEncodeImg().isEmpty() ){
Tenes que usar @Valid el DTO que recibe el controller y anotaciones de validación sobre el DTO, revisá los ejemplos de tus compañeros

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +			if(!(slideRequestDTO.getOrder()==null)){
idem al comentario anterior de @Valid en Controller

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +				if(existSlideByOrder(slideRequestDTO.getOrder())){
Esto lo tenes que hacer antes de buscar la slide actual, sino desperdicias recursos de BBDD

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +        Long l= slideRequestDTO.getOrganizationId();
Las variables tienen que ser declarativas, "l" como nombre no esta bien

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/utils/ImageHelper.java
> +        } catch (IllegalStateException e) {
manejar bien las excepciones por excepciones custom que apunten al problema

2022-05-28 20:18 UTC, duccisg commented on src/main/java/com/alkemy/somosmas/utils/ImageHelper.java
> +            e.printStackTrace();
esto esta mal, no se puede capturar una excepcion y no hacer nada

2022-05-29 03:35 UTC, cristhianGutierrez commented on src/main/java/com/alkemy/somosmas/services/impl/SlideServiceImpl.java
> +			if(!(slideRequestDTO.getOrder()==null)){
en el metodo update valida:  si es diferente de null  settea el atributo order de lo contrario no actualiza el campo order.

2022-05-29 05:44 UTC, cristhianGutierrez commented
[evidenciaSlide.pdf](https://github.com/alkemyTech/OT193-Server/files/8792735/evidenciaSlide.pdf)

2022-05-31 02:49 UTC, duccisg approved these changes

2022-05-31 02:52 UTC, duccisg approved these changes

2022-05-31 02:52 UTC, merged